version: '2'
services:
  db:
    image: postgres
    volumes:
      - 'db:/usr/local/var/postgres/pg_data/'
  redis:
    image: redis:3.0.7
    ports: ['6379:6379']
    volumes:
      - 'redis:/usr/local/var/db/redis/'
    depends_on:
      - 'db'
  api:
    image: 'scprdev/resound-api'
    ports: ['3000:3000']
    depends_on:
      - 'redis'
      - 'db'
    environment:
      RAILS_ENV: $RAILS_ENV
      AWS_REGION: $AWS_REGION
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_BUCKET: $AWS_BUCKET
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID
      AUTH0_DOMAIN: $AUTH0_DOMAIN
      AUTH0_CALLBACK_URL: $AUTH0_CALLBACK_URL
      AUTH0_AUDIENCE: $AUTH0_AUDIENCE
      ALLOWED_CORS_URL: $ALLOWED_CORS_URL
      REDIS_URL: 'redis://redis:6379'
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PW: $DB_PW
      DB_HOST: $DB_HOST
    volumes:
      - 'api:/app/'
    command: foreman start
  web:
    image: 'scprdev/resound-store-manage'
    ports: ['80:8000']
    environment:
      AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID
      AUTH0_DOMAIN: $AUTH0_DOMAIN
      AUTH0_CALLBACK_URL: $AUTH0_CALLBACK_URL
      AUTH0_AUDIENCE: $AUTH0_AUDIENCE
      RESOUND_API_URL: $RESOUND_API_URL
volumes:
  redis:
  db:
  api:
